{
 "title": "TCC - Benchmark",
 "time": { "from": "2022-09-03T14:58:06.371Z", "to": "2022-09-03T17:25:11.329Z" },
 "panels": [
  { "title": "Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    { "expr": "rate(say_hello_req_count[1m])", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(say_hello_latency_bucket[1m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n    rate(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{container=\"server\"}[1m])\n) by (pod)\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Latency Average",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(say_hello_latency_sum[$__rate_interval])) / sum(rate(say_hello_latency_count[$__rate_interval]))",
     "legendFormat": "avg"
    }
   ]
  },
  { "title": "Traefik", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n    rate(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{container=\"server\"}[1m])\n) by (pod)\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Exported Service Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum(traefik_service_open_connections{exported_service=\"default-server-088a5d46a313ca2af907@kubernetescrd\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(traefik_service_request_duration_seconds_sum{exported_service=\"joao-tcc-server-c794b57e598b850b4a18@kubernetescrd\", code=\"200\"}[$__rate_interval])) / sum(rate(traefik_service_request_duration_seconds_count{exported_service=\"joao-tcc-server-c794b57e598b850b4a18@kubernetescrd\", code=\"200\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Traefik connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum(traefik_entrypoint_open_connections{endpoint=\"web\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}