apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghz
spec:
  storageClassName: do-block-storage-xfs-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
