version: "3"

services:
  server:
    image: ghcr.io/jfmrm/benchmark-server
    ports:
    - "50051:50051"

  load-tool-web:
    build:
      context: .
      dockerfile: docker/load-tool-web/Dockerfile
    ports:
      - "8080:80"
