version: "3"

services:
  server:
    container_name: server
    image: ghcr.io/jfmrm/benchmark-server
    ports:
      - "50051:50051"

  ghz-web-db:
    container_name: ghz-web-db
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: ghz
    ports:
      - "5432:5432"

  ghz-web:
    container_name: ghz-web
    build:
      context: .
      dockerfile: docker/load-tool-web/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./docker/load-tool-web/config.toml:/config.toml
