version: "3"

services:
  server:
    container_name: server
    image: ghcr.io/jfmrm/benchmark-server
    ports:
      - "50051:50051"

  ghz:
    container_name: ghz
    image: obvionaoe/ghz
    volumes:
      - ./docker/ghz:/configs
      - ./helloworld:/helloworld
    command: "--config=/configs/step-down.json"
