apiVersion: batch/v1
kind: Job
metadata:
  name: constant-load
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      volumes:
      - name: output
        persistentVolumeClaim:
          claimName: ghz
      containers:
      - name: ghz
        image: ghcr.io/jfmrm/ghz:latest
        command: ["ghz", "--config=/ghz/config/constant.json", "--lb-strategy=round_robin", "--output=/results/client-side/constant-load-cslb-700.html", "--format=html", "--rps=700", "dns:///server-headless:50051"]
        volumeMounts:
        - name: output
          mountPath: /results/client-side
      restartPolicy: OnFailure
