apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: server
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`server.45.55.106.187.nip.io`) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: server-proxy
          port: 50051
          kind: Service
          scheme: h2c
