apiVersion: batch/v1
kind: Job
metadata:
  name: step-up-load
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: ghz
        image: ghcr.io/jfmrm/ghz:latest
        command: ["ghz", "--config=/ghz/config/step-up.json", "server:50051"]
      restartPolicy: OnFailure
