apiVersion: batch/v1
kind: Job
metadata:
  name: constant-load
spec:
  ttlSecondsAfterFinished: 1000
  template:
    spec:
      volumes:
      - name: output
        persistentVolumeClaim:
          claimName: ghz
      containers:
      - name: ghz
        image: ghcr.io/jfmrm/ghz:latest
        command: 
          - "ghz --config=/ghz/config/constant.json --output=/results/proxy/constant-load-private-ip-1000.html --rps=1000 --format=html server.11.0.212.161.nip.io:80"
          - sleep 120
          -
        volumeMounts:
        - name: output
          mountPath: /results/proxy
      restartPolicy: OnFailure
