apiVersion: batch/v1
kind: Job
metadata:
  name: step-up-load
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: ghz
        image: ghcr.io/jfmrm/ghz:latest
        command: ["ghz", "--config=/ghz/config/constant.json", "45.55.106.187.nip.io:80"]
      restartPolicy: OnFailure
