apiVersion: batch/v1
kind: Job
metadata:
  name: step-up-load
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      volumes:
      - name: output
        persistentVolumeClaim:
          claimName: ghz
      containers:
      - name: ghz
        image: ghcr.io/jfmrm/ghz:latest
        command: ["ghz", "--config=/ghz/config/step-up.json", "--output=/results/proxy/step-up.html", "--format=html" ,"server.45.55.106.187.nip.io:80"]
        volumeMounts:
        - name: output
          mountPath: /results/proxy
      restartPolicy: OnFailure
