apiVersion: batch/v1
kind: Job
metadata:
  name: step-up-load
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      volumes:
      - name: output
        persistentVolumeClaim:
          claimName: ghz
      containers:
      - name: ghz
        image: ghcr.io/jfmrm/ghz:latest
        command: ["ghz", "--config=/ghz/config/step-up.json", "--output=/results/proxy/step-up-private-ip.html", "--format=html" ,"server.11.0.212.161.nip.io:80"]
        volumeMounts:
        - name: output
          mountPath: /results/proxy
      restartPolicy: OnFailure
