apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: monitoring
  name: traefik
spec:
  endpoints:
  - path: /metrics
    port: web
    scheme: http
  selector:
    matchLabels:
      app.kubernetes.io/instance: traefik
